version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASS}
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-postgres:/var/lib/postgresql
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: metabase_db
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - metanet1
    restart: always

volumes:
  db-postgres:

networks:
  metanet1:
    driver: bridge
